### ISSUE TITLE
make release error

### ISSUE THREAD

**Issue by maaaay** [sihangliu/pmtest#2]
Hi, sihang
Error occurred when executing make.
/usr/bin/ld: build/objects/pmtest.o: undefined reference to symbol '__tls_get_addr@@GLIBC_2.3'
//usr/lib64/ld-linux-x86-64.so.2: error adding symbols: DSO missing from command line

CentOS Linux release 7.6.1810 (Core) 
glibc-2.17-260.el7_6.3.x86_64
gcc/g++ version : 4.8.5

**Comment by warsier** [comment]
Hi,
I am sorry that we did not do an extensive testing on a lot of different systems, and I may not be able to help you locate exactly how the error happens. But I guess there are still something worth trying.
Could you follow the suggestions in [this link](https://stackoverflow.com/questions/28198965/how-to-resolve-tls-get-addrglibc-2-3-error-on-compiling-gcc-itself), and check if upgrading glibc to a newer version works?
